In [1]:
from alpha_vantage.timeseries import TimeSeries
import matplotlib.pyplot as plt
import sys
import pandas as pd

whole_data = []

symbols = ["ISRG","BDX","ALC","WST","RMD","UNH","ELV", "CVS","CI","HUM","NVO","VRTX","REGN","SGEN","MRNA","PFE","JNJ","LLY","AZN", "MRK"]

for symbol in symbols:
    ts = TimeSeries(key='9SJ9JBPTJZMWVIZW', output_format='pandas')
    data, meta_data = ts.get_daily(symbol=symbol, outputsize='full')
    data_df = pd.DataFrame(data)
    
# data_df.info()
    data_df = data_df.sort_index()
    
# Set the 'date' column as the index
    start_date = '2018-01-01'
    end_date = '2023-11-29'
    
    filtered_data = pd.DataFrame(data_df.loc[start_date:end_date])
# stock_data = data_date_changed

    filtered_data["Ticker"] = symbol
    whole_data.append(filtered_data)
    
print(whole_data)

[            1. open  2. high   3. low  4. close  5. volume Ticker
date
2018-01-02   367.89  375.810  365.110    375.25   694925.0   ISRG
2018-01-03   377.12  384.170  375.010    383.82   767711.0   ISRG
2018-01-04   385.73  389.480  375.090    376.92   889251.0   ISRG
2018-01-05   380.88  380.880  375.800    379.01   672195.0   ISRG
2018-01-08   378.72  392.640  377.210    391.86   938767.0   ISRG
...             ...      ...      ...       ...        ...    ...
2023-11-22   315.00  317.390  313.920    315.80  1199862.0   ISRG
2023-11-24   316.95  318.260  316.000    318.01   601268.0   ISRG
2023-11-27   314.68  316.000  312.020    314.98  1084261.0   ISRG
2023-11-28   311.84  312.760  309.260    310.95  1558995.0   ISRG
2023-11-29   312.00  316.305  309.965    310.76  1389053.0   ISRG

[1488 rows x 6 columns],             1. open  2. high    3. low  4. close  5. volume Ticker
date
2018-01-02   215.09   220.04  215.0900    217.84  2654247.0    BDX
2018-01-03   219.43   221.28  218.7800    219.99  1735200.0    BDX
2018-01-04   219.34   221.77  219.2100    220.99  1331704.0    BDX
2018-01-05   222.37   223.55  221.2600    222.08  1423701.0    BDX
2018-01-08   222.03   222.68  220.2600    221.40  1736412.0    BDX
...             ...      ...       ...       ...        ...    ...
2023-11-22   237.37   238.05  235.7400    236.80  1929714.0    BDX
2023-11-24   236.65   238.90  236.4106    238.89   780792.0    BDX
2023-11-27   238.66   240.40  237.4100    238.86  1746312.0    BDX
2023-11-28   238.72   239.95  237.1900    237.28  1475259.0    BDX
2023-11-29   237.10   238.83  235.6300    235.69  2722747.0    BDX

[1488 rows x 6 columns],             1. open  2. high   3. low  4. close   5. volume Ticker
date
2019-04-09    57.95    58.73  57.6700     58.04  10608311.0    ALC
2019-04-10    56.97    57.94  56.8800     57.30   5456394.0    ALC
2019-04-11    55.82    56.02  55.2300     55.60   5487408.0    ALC
2019-04-12    54.06    54.81  53.7800     54.43   4701567.0    ALC
2019-04-15    55.09    56.22  54.7300     55.75   4369887.0    ALC
...             ...      ...      ...       ...         ...    ...
2023-11-22    73.17    73.47  72.6000     72.84    870031.0    ALC
2023-11-24    73.30    73.62  72.9800     73.52    523466.0    ALC
2023-11-27    73.38    73.69  73.2300     73.24    770928.0    ALC
2023-11-28    73.14    74.05  73.0694     73.53    892907.0    ALC
2023-11-29    74.33    75.17  74.3200     74.66   1127335.0    ALC

[1170 rows x 6 columns],             1. open  2. high  3. low  4. close  5. volume Ticker
date
2018-01-02    99.00   99.810   98.43     99.50   334972.0    WST
2018-01-03    99.68   99.980   99.09     99.62   194431.0    WST
2018-01-04    99.87  100.160   98.85     99.59   367509.0    WST
2018-01-05    99.90  101.340   99.90    100.84   156619.0    WST
2018-01-08   100.81  101.600  100.24    101.41   153870.0    WST
...             ...      ...     ...       ...        ...    ...
2023-11-22   356.52  358.485  350.46    351.17   502026.0    WST
2023-11-24   352.15  354.350  350.30    353.26   114787.0    WST
2023-11-27   352.14  355.255  351.15    353.90   339907.0    WST
2023-11-28   352.35  356.790  350.74    352.42   468210.0    WST
2023-11-29   355.43  355.970  348.55    348.92   378334.0    WST

[1488 rows x 6 columns],             1. open  2. high   3. low  4. close  5. volume Ticker
date
2018-01-02    85.20    86.12   84.930     85.53   328464.0    RMD
2018-01-03    85.38    86.65   85.310     86.42   480780.0    RMD
2018-01-04    86.54    86.85   86.230     86.54   627529.0    RMD
2018-01-05    86.59    87.69   86.120     87.69   531585.0    RMD
2018-01-08    87.67    88.49   87.240     88.19   713552.0    RMD
...             ...      ...      ...       ...        ...    ...
2023-11-22   153.99   154.24  152.080    152.61   428156.0    RMD
2023-11-24   152.64   154.07  152.545    153.88   301301.0    RMD
2023-11-27   152.67   153.73  152.320    152.57   541334.0    RMD
2023-11-28   151.95   155.99  151.950    155.68  1358140.0    RMD
2023-11-29   158.50   164.10  158.480    158.85  1762127.0    RMD

[1488 rows x 6 columns],             1. open   2. high    3. low  4. close  5. volume Ticker
date
2018-01-02   221.02  222.4500  220.0000    221.16  3276075.0    UNH
2018-01-03   221.62  223.8100  220.5200    223.48  2353723.0    UNH
2018-01-04   224.34  226.1000  224.1700    224.45  2643607.0    UNH
2018-01-05   225.19  229.0500  224.7200    228.73  2385007.0    UNH
2018-01-08   228.13  228.7100  224.6100    224.76  2730381.0    UNH
...             ...       ...       ...       ...        ...    ...
2023-11-22   542.97  544.4000  540.2550    543.76  2234478.0    UNH
2023-11-24   544.93  547.5900  542.8100    547.10  1134977.0    UNH
2023-11-27   547.10  550.8891  541.5347    543.59  2675815.0    UNH
2023-11-28   545.63  545.8200  540.0700    540.53  2859309.0    UNH
2023-11-29   530.00  541.8600  528.6500    534.98  4549977.0    UNH

[1488 rows x 6 columns],             1. open  2. high   3. low  4. close  5. volume Ticker
date
2018-01-02   225.00  226.600  223.750    226.00  1175943.0    ELV
2018-01-03   227.87  229.550  225.060    229.15  1302005.0    ELV
2018-01-04   229.60  231.410  228.860    230.21  1017834.0    ELV
2018-01-05   230.19  234.540  229.880    234.34  1345404.0    ELV
2018-01-08   233.49  233.490  230.730    231.82  1629128.0    ELV
...             ...      ...      ...       ...        ...    ...
2023-11-22   472.63  481.060  472.630    479.97   979823.0    ELV
2023-11-24   479.73  482.200  478.000    478.73   309997.0    ELV
2023-11-27   478.95  481.830  475.865    477.41  1048150.0    ELV
2023-11-28   477.32  480.210  475.290    475.49   767739.0    ELV
2023-11-29   469.61  472.689  462.740    465.36  1687845.0    ELV

[1488 rows x 6 columns],             1. open  2. high  3. low  4. close   5. volume Ticker
date
2018-01-02    73.06   74.030   72.87     73.52   5697104.0    CVS
2018-01-03    73.73   73.900   73.06     73.20   6136065.0    CVS
2018-01-04    75.19   76.670   74.68     75.13  13695605.0    CVS
2018-01-05    76.31   78.560   76.14     78.45  14240985.0    CVS
2018-01-08    78.32   78.780   77.15     77.77   9581927.0    CVS
...             ...      ...     ...       ...         ...    ...
2023-11-22    68.34   69.230   68.34     69.14   4421860.0    CVS
2023-11-24    68.75   69.485   68.75     69.42   2215900.0    CVS
2023-11-27    69.37   69.615   68.62     68.74   6334283.0    CVS
2023-11-28    68.86   69.530   68.60     69.32   4291910.0    CVS
2023-11-29    68.74   68.910   66.85     66.90   9856309.0    CVS

[1488 rows x 6 columns],             1. open   2. high  3. low  4. close  5. volume Ticker
date
2018-01-02   204.14  204.9800  202.34    202.56  1114845.0     CI
2018-01-03   202.52  206.3200  201.30    205.96  1360756.0     CI
2018-01-04   206.07  208.0400  206.07    207.04   870097.0     CI
2018-01-05   207.91  211.0800  207.60    210.55   742822.0     CI
2018-01-08   209.77  210.4900  207.71    208.22  1100255.0     CI
...             ...       ...     ...       ...        ...    ...
2023-11-22   286.59  289.1600  285.95    288.31   905931.0     CI
2023-11-24   288.50  290.7800  287.33    287.85   416247.0     CI
2023-11-27   287.97  289.6566  285.01    286.26  1220239.0     CI
2023-11-28   287.03  289.0400  285.35    286.08  1437048.0     CI
2023-11-29   283.15  287.6000  262.51    262.87  7568667.0     CI

[1488 rows x 6 columns],             1. open  2. high  3. low  4. close  5. volume Ticker
date
2018-01-02   249.36   252.86  248.01    251.64   795680.0    HUM
2018-01-03   252.03   256.60  250.25    251.28  1212312.0    HUM
2018-01-04   252.86   259.97  252.86    258.36  1345052.0    HUM
2018-01-05   258.42   264.90  258.39    264.33  1212204.0    HUM
2018-01-08   263.88   263.88  257.05    258.55  1303905.0    HUM
...             ...      ...     ...       ...        ...    ...
2023-11-22   510.65   516.83  507.00    515.60   892112.0    HUM
2023-11-24   519.00   520.79  514.45    518.26   312001.0    HUM
2023-11-27   520.31   527.18  510.43    510.71   986348.0    HUM
2023-11-28   511.84   515.39  510.37    510.45   718133.0    HUM
2023-11-29   496.01   526.47  480.36    482.41  5041754.0    HUM

[1488 rows x 6 columns],             1. open  2. high    3. low  4. close  5. volume Ticker
date
2018-01-02    54.49    54.52   53.9900     54.16   741402.0    NVO
2018-01-03    54.54    54.75   54.3800     54.68   752381.0    NVO
2018-01-04    54.65    54.68   54.3600     54.49   604232.0    NVO
2018-01-05    54.47    54.76   54.4500     54.74   645393.0    NVO
2018-01-08    54.56    54.74   54.3800     54.69   614045.0    NVO
...             ...      ...       ...       ...        ...    ...
2023-11-22   103.06   103.71  102.1400    103.26  2692858.0    NVO
2023-11-24   104.23   105.69  104.1468    105.45  4598705.0    NVO
2023-11-27   104.88   105.44  103.6900    103.87  4746037.0    NVO
2023-11-28   101.87   102.25  101.0300    101.43  5147734.0    NVO
2023-11-29   101.55   102.31  100.8600    102.00  2664643.0    NVO

[1488 rows x 6 columns],             1. open  2. high    3. low  4. close  5. volume Ticker
date
2018-01-02   150.00   153.30  147.7200    152.91  1322844.0   VRTX
2018-01-03   153.50   153.50  148.5800    152.01  1601041.0   VRTX
2018-01-04   153.39   153.97  151.6300    153.07  1340181.0   VRTX
2018-01-05   155.54   157.35  154.1000    155.69  1857324.0   VRTX
2018-01-08   155.15   157.21  153.3500    156.89  1917306.0   VRTX
...             ...      ...       ...       ...        ...    ...
2023-11-22   357.06   358.50  350.0269    353.23   913465.0   VRTX
2023-11-24   354.95   355.41  350.4400    353.04   658708.0   VRTX
2023-11-27   353.95   354.45  349.1600    350.19  1308575.0   VRTX
2023-11-28   350.32   353.03  346.2850    347.04  1154122.0   VRTX
2023-11-29   347.50   353.60  346.6800    351.00  1497318.0   VRTX

[1488 rows x 6 columns],             1. open  2. high   3. low  4. close  5. volume Ticker
date
2018-01-02   379.48   384.81  377.105    382.60   615937.0   REGN
2018-01-03   383.14   396.78  381.140    393.78   687986.0   REGN
2018-01-04   394.50   394.95  382.400    382.95   644172.0   REGN
2018-01-05   385.85   388.79  381.950    385.10   447465.0   REGN
2018-01-08   384.40   387.33  371.260    372.52  1067679.0   REGN
...             ...      ...      ...       ...        ...    ...
2023-11-22   802.64   807.46  798.090    799.73   233085.0   REGN
2023-11-24   803.98   803.98  795.020    798.30   171558.0   REGN
2023-11-27   802.00   805.00  793.180    798.08   440182.0   REGN
2023-11-28   796.23   801.63  792.570    801.14   446730.0   REGN
2023-11-29   804.17   814.30  800.240    808.59   627657.0   REGN

[1488 rows x 6 columns],             1. open  2. high    3. low  4. close  5. volume Ticker
date
2018-01-02    53.64   56.510   53.6300     56.13   945253.0   SGEN
2018-01-03    56.30   57.130   55.5450     56.61   540620.0   SGEN
2018-01-04    56.74   56.875   55.0400     55.53   577182.0   SGEN
2018-01-05    55.98   55.980   54.8700     55.01   500198.0   SGEN
2018-01-08    55.12   55.230   54.2950     54.68   807795.0   SGEN
...             ...      ...       ...       ...        ...    ...
2023-11-22   214.62  214.620  212.8200    213.07   845100.0   SGEN
2023-11-24   213.27  215.000  212.9700    214.45   449846.0   SGEN
2023-11-27   214.50  214.960  214.0500    214.42   767864.0   SGEN
2023-11-28   214.42  214.690  213.8397    214.16   873892.0   SGEN
2023-11-29   214.33  214.650  213.5000    213.52   742965.0   SGEN

[1488 rows x 6 columns],             1. open  2. high  3. low  4. close   5. volume Ticker
date
2018-12-07    22.00   22.750  18.510     18.60  12995569.0   MRNA
2018-12-10    18.90   19.439  18.000     18.80   4233345.0   MRNA
2018-12-11    20.55   20.660  17.990     18.01   3435271.0   MRNA
2018-12-12    18.55   19.480  18.020     18.68   2590873.0   MRNA
2018-12-13    19.25   19.290  18.680     18.76   1608629.0   MRNA
...             ...      ...     ...       ...         ...    ...
2023-11-22    78.06   78.670  76.835     78.17   2203917.0   MRNA
2023-11-24    78.66   81.120  77.770     78.52   2152974.0   MRNA
2023-11-27    78.36   78.360  75.660     77.72   2960110.0   MRNA
2023-11-28    77.32   78.250  75.840     78.18   2240038.0   MRNA
2023-11-29    78.95   80.890  78.850     79.01   2569849.0   MRNA

[1253 rows x 6 columns],             1. open  2. high  3. low  4. close   5. volume Ticker
date
2018-01-02    36.38  36.5200  36.240     36.44  14503068.0    PFE
2018-01-03    36.45  36.7700  36.230     36.71  13453369.0    PFE
2018-01-04    36.71  36.9200  36.600     36.79  12350187.0    PFE
2018-01-05    36.82  36.8800  36.610     36.86  12380571.0    PFE
2018-01-08    36.72  36.8000  36.330     36.45  18908870.0    PFE
...             ...      ...     ...       ...         ...    ...
2023-11-22    30.39  30.5769  30.140     30.32  19230183.0    PFE
2023-11-24    30.38  30.7000  30.380     30.50  11129739.0    PFE
2023-11-27    30.75  30.7500  30.030     30.14  26066748.0    PFE
2023-11-28    30.11  30.1100  29.635     29.69  29497713.0    PFE
2023-11-29    29.77  30.2200  29.725     30.08  26185160.0    PFE

[1488 rows x 6 columns],             1. open   2. high  3. low  4. close  5. volume Ticker
date
2018-01-02   139.66  139.9500  138.72    139.23  6835739.0    JNJ
2018-01-03   139.36  140.6800  138.90    140.56  5241755.0    JNJ
2018-01-04   140.45  141.1400  140.22    140.55  4777518.0    JNJ
2018-01-05   140.69  141.8200  140.28    141.71  5900718.0    JNJ
2018-01-08   141.70  142.0000  140.92    141.89  4980217.0    JNJ
...             ...       ...     ...       ...        ...    ...
2023-11-22   151.63  152.0400  150.39    150.82  4635503.0    JNJ
2023-11-24   150.86  152.6794  150.86    152.50  3351448.0    JNJ
2023-11-27   152.29  152.3200  150.97    151.28  6449740.0    JNJ
2023-11-28   151.40  151.8100  150.84    151.63  5909044.0    JNJ
2023-11-29   151.33  152.2000  151.07    152.11  5190026.0    JNJ

[1488 rows x 6 columns],             1. open   2. high    3. low  4. close  5. volume Ticker
date
2018-01-02    84.46   85.0000   84.0600     84.68  3455236.0    LLY
2018-01-03    84.74   85.4200   84.2700     85.14  3068865.0    LLY
2018-01-04    85.28   85.8000   84.7400     85.52  2459830.0    LLY
2018-01-05    86.09   86.7500   85.9300     86.57  2910172.0    LLY
2018-01-08    86.69   86.7100   85.4000     86.13  3015436.0    LLY
...             ...       ...       ...       ...        ...    ...
2023-11-22   595.40  599.1800  586.7500    595.09  2052682.0    LLY
2023-11-24   598.36  603.5000  596.9813    601.10  1341674.0    LLY
2023-11-27   601.17  603.6900  591.1400    591.53  2630713.0    LLY
2023-11-28   592.00  595.3800  589.3600    591.60  1793933.0    LLY
2023-11-29   592.20  594.5399  584.4401    591.86  1908649.0    LLY

[1488 rows x 6 columns],             1. open  2. high  3. low  4. close  5. volume Ticker
date
2018-01-02    35.24   35.440  34.950     35.38  6107393.0    AZN
2018-01-03    35.22   35.510  35.160     35.45  4195423.0    AZN
2018-01-04    35.51   35.600  35.280     35.50  3870932.0    AZN
2018-01-05    35.58   35.920  35.500     35.87  3336132.0    AZN
2018-01-08    35.72   35.770  35.420     35.62  1826353.0    AZN
...             ...      ...     ...       ...        ...    ...
2023-11-22    63.71   63.920  63.275     63.61  4837176.0    AZN
2023-11-24    64.33   64.735  64.250     64.50  2139434.0    AZN
2023-11-27    63.90   63.990  63.360     63.66  4340553.0    AZN
2023-11-28    63.20   63.530  63.090     63.30  5556087.0    AZN
2023-11-29    64.14   64.335  63.710     64.12  8493239.0    AZN

[1488 rows x 6 columns],             1. open   2. high  3. low  4. close   5. volume Ticker
date
2018-01-02    56.59   56.7500   56.05     56.22  10048319.0    MRK
2018-01-03    56.23   56.2600   55.96     56.14  10573680.0    MRK
2018-01-04    56.44   57.4200   56.38     57.05  14991734.0    MRK
2018-01-05    57.39   57.3900   56.59     56.99   9482639.0    MRK
2018-01-08    57.21   57.2500   56.50     56.66  10504085.0    MRK
...             ...       ...     ...       ...         ...    ...
2023-11-22   102.20  102.6800  101.11    101.68   5724130.0    MRK
2023-11-24   102.26  102.5136  101.44    101.87   3167952.0    MRK
2023-11-27   101.91  102.1500  100.70    101.43   7356536.0    MRK
2023-11-28   101.31  101.3500  100.01    100.18   8738483.0    MRK
2023-11-29   100.28  101.1700   99.80    101.13  10286779.0    MRK

[1488 rows x 6 columns]]

In [2]:
# Concatenate the list of dataframes into a single dataframe
result_df = pd.concat(whole_data)

# Save the dataframe to a CSV file
result_df.to_csv('Healthcare_Stock_Data.csv', index=True)

In [3]:
# Read the CSV file into a DataFrame
healthcare_stock_data = pd.read_csv('Healthcare_Stock_Data.csv')

# Create dictionaries to map symbols to sectors and industries
symbol_to_sector = {
    "ISRG": "Healthcare",
    "BDX": "Healthcare",
    "ALC": "Healthcare",
    "WST": "Healthcare",
    "RMD": "Healthcare",
    "UNH": "Healthcare",
    "ELV": "Healthcare",
    "CVS": "Healthcare",
    "CI": "Healthcare",
    "HUM": "Healthcare",
    "NVO": "Healthcare",
    "VRTX": "Healthcare",
    "REGN": "Healthcare",
    "SGEN": "Healthcare",
    "MRNA": "Healthcare",
    "PFE": "Healthcare",
    "JNJ": "Healthcare",
    "LLY": "Healthcare",
    "AZN": "Healthcare",
    "MRK": "Healthcare",
}

symbol_to_industry = {
    "ISRG": "Medical Instruments & supplies",
    "BDX": "Medical Instruments & supplies",
    "ALC": "Medical Instruments & supplies",
    "WST": "Medical Instruments & supplies",
    "RMD": "Medical Instruments & supplies",
    "UNH": "Healthcare plans",
    "ELV": "Healthcare plans",
    "CVS": "Healthcare plans",
    "CI": "Healthcare plans",
    "HUM": "Healthcare plans",
    "NVO": "Biotechnology",
    "VRTX": "Biotechnology",
    "REGN": "Biotechnology",
    "SGEN": "Biotechnology",
    "MRNA": "Biotechnology",
    "PFE": "Drug Manufacturers",
    "JNJ": "Drug Manufacturers",
    "LLY": "Drug Manufacturers",
    "AZN": "Drug Manufacturers",
    "MRK": "Drug Manufacturers",
}

# Add 'Sector' and 'Industry' columns based on the mappings
healthcare_stock_data['Sector'] = healthcare_stock_data['Ticker'].map(symbol_to_sector)
healthcare_stock_data['Industry'] = healthcare_stock_data['Ticker'].map(symbol_to_industry)

# Display the updated DataFrame
healthcare_stock_data

,date,1. open,2. high,3. low,4. close,5. volume,Ticker,Sector,Industry
0,2018-01-02,367.89,375.8100,365.11,375.25,694925.0,ISRG,Healthcare,Medical Instruments & supplies
1,2018-01-03,377.12,384.1700,375.01,383.82,767711.0,ISRG,Healthcare,Medical Instruments & supplies
2,2018-01-04,385.73,389.4800,375.09,376.92,889251.0,ISRG,Healthcare,Medical Instruments & supplies
3,2018-01-05,380.88,380.8800,375.80,379.01,672195.0,ISRG,Healthcare,Medical Instruments & supplies
4,2018-01-08,378.72,392.6400,377.21,391.86,938767.0,ISRG,Healthcare,Medical Instruments & supplies
...,...,...,...,...,...,...,...,...,...
29202,2023-11-22,102.20,102.6800,101.11,101.68,5724130.0,MRK,Healthcare,Drug Manufacturers
29203,2023-11-24,102.26,102.5136,101.44,101.87,3167952.0,MRK,Healthcare,Drug Manufacturers
29204,2023-11-27,101.91,102.1500,100.70,101.43,7356536.0,MRK,Healthcare,Drug Manufacturers
29205,2023-11-28,101.31,101.3500,100.01,100.18,8738483.0,MRK,Healthcare,Drug Manufacturers
29206,2023-11-29,100.28,101.1700,99.80,101.13,10286779.0,MRK,Healthcare,Drug Manufacturers

In [4]:
# Create a new DataFrame with reordered columns
df_reordered = healthcare_stock_data[['Ticker', 'Sector', 'Industry', '1. open', '2. high', '3. low', '4. close', '5. volume']]

# Rename columns for clarity
df_reordered.columns = ['Ticker', 'Sector', 'Industry', 'Open', 'High', 'Low', 'Close', 'Volume']

# Display the updated DataFrame
df_reordered

,Ticker,Sector,Industry,Open,High,Low,Close,Volume
0,ISRG,Healthcare,Medical Instruments & supplies,367.89,375.8100,365.11,375.25,694925.0
1,ISRG,Healthcare,Medical Instruments & supplies,377.12,384.1700,375.01,383.82,767711.0
2,ISRG,Healthcare,Medical Instruments & supplies,385.73,389.4800,375.09,376.92,889251.0
3,ISRG,Healthcare,Medical Instruments & supplies,380.88,380.8800,375.80,379.01,672195.0
4,ISRG,Healthcare,Medical Instruments & supplies,378.72,392.6400,377.21,391.86,938767.0
...,...,...,...,...,...,...,...,...
29202,MRK,Healthcare,Drug Manufacturers,102.20,102.6800,101.11,101.68,5724130.0
29203,MRK,Healthcare,Drug Manufacturers,102.26,102.5136,101.44,101.87,3167952.0
29204,MRK,Healthcare,Drug Manufacturers,101.91,102.1500,100.70,101.43,7356536.0
29205,MRK,Healthcare,Drug Manufacturers,101.31,101.3500,100.01,100.18,8738483.0
29206,MRK,Healthcare,Drug Manufacturers,100.28,101.1700,99.80,101.13,10286779.0

In [5]:
# Save the dataframe to a CSV file
df_reordered.to_csv('../Datasets/Healthcare_Stock_Data4.csv', index=False)