In [4]:
from alpha_vantage.timeseries import TimeSeries
import matplotlib.pyplot as plt
import sys
import pandas as pd

whole_data = []

symbols = ["ISRG","BDX","ALC","WST","RMD","UNH","ELV", "CVS","CI","HUM","NVO","VRTX","REGN","SGEN","MRNA","PFE","JNJ","LLY","AZN", "MRK"]

for symbol in symbols:
    ts = TimeSeries(key='9SJ9JBPTJZMWVIZW', output_format='pandas')
    data, meta_data = ts.get_daily(symbol=symbol, outputsize='full')
    data_df = pd.DataFrame(data)
    
# data_df.info()
    data_df = data_df.sort_index()
    
# Set the 'date' column as the index
    start_date = '2018-01-01'
    end_date = '2023-12-04'
    
    filtered_data = pd.DataFrame(data_df.loc[start_date:end_date])
# stock_data = data_date_changed

    filtered_data["Ticker"] = symbol
    whole_data.append(filtered_data)
    
print(whole_data)

[            1. open  2. high   3. low  4. close  5. volume Ticker
date
2018-01-02   367.89  375.810  365.110    375.25   694925.0   ISRG
2018-01-03   377.12  384.170  375.010    383.82   767711.0   ISRG
2018-01-04   385.73  389.480  375.090    376.92   889251.0   ISRG
2018-01-05   380.88  380.880  375.800    379.01   672195.0   ISRG
2018-01-08   378.72  392.640  377.210    391.86   938767.0   ISRG
...             ...      ...      ...       ...        ...    ...
2023-11-28   311.84  312.760  309.260    310.95  1558995.0   ISRG
2023-11-29   312.00  316.305  309.965    310.76  1389053.0   ISRG
2023-11-30   310.76  311.990  304.700    310.84  2437496.0   ISRG
2023-12-01   310.59  315.640  308.730    315.20  1388826.0   ISRG
2023-12-04   311.92  315.930  308.910    311.84  1431186.0   ISRG

[1491 rows x 6 columns],             1. open  2. high  3. low  4. close  5. volume Ticker
date
2018-01-02   215.09   220.04  215.09    217.84  2654247.0    BDX
2018-01-03   219.43   221.28  218.78    219.99  1735200.0    BDX
2018-01-04   219.34   221.77  219.21    220.99  1331704.0    BDX
2018-01-05   222.37   223.55  221.26    222.08  1423701.0    BDX
2018-01-08   222.03   222.68  220.26    221.40  1736412.0    BDX
...             ...      ...     ...       ...        ...    ...
2023-11-28   238.72   239.95  237.19    237.28  1475259.0    BDX
2023-11-29   237.10   238.83  235.63    235.69  2722747.0    BDX
2023-11-30   236.28   237.00  234.80    236.18  3275869.0    BDX
2023-12-01   236.07   238.50  235.34    238.25  1512416.0    BDX
2023-12-04   237.32   238.56  237.10    237.57  1574436.0    BDX

[1491 rows x 6 columns],             1. open  2. high   3. low  4. close   5. volume Ticker
date
2019-04-09    57.95  58.7300  57.6700     58.04  10608311.0    ALC
2019-04-10    56.97  57.9400  56.8800     57.30   5456394.0    ALC
2019-04-11    55.82  56.0200  55.2300     55.60   5487408.0    ALC
2019-04-12    54.06  54.8100  53.7800     54.43   4701567.0    ALC
2019-04-15    55.09  56.2200  54.7300     55.75   4369887.0    ALC
...             ...      ...      ...       ...         ...    ...
2023-11-28    73.14  74.0500  73.0694     73.53    892907.0    ALC
2023-11-29    74.33  75.1700  74.3200     74.66   1127335.0    ALC
2023-11-30    74.78  75.8600  74.5150     75.63    887178.0    ALC
2023-12-01    74.98  75.9197  74.9800     75.85    974866.0    ALC
2023-12-04    72.82  73.9300  72.4000     73.23   1462299.0    ALC

[1173 rows x 6 columns],             1. open  2. high  3. low  4. close  5. volume Ticker
date
2018-01-02    99.00    99.81   98.43     99.50   334972.0    WST
2018-01-03    99.68    99.98   99.09     99.62   194431.0    WST
2018-01-04    99.87   100.16   98.85     99.59   367509.0    WST
2018-01-05    99.90   101.34   99.90    100.84   156619.0    WST
2018-01-08   100.81   101.60  100.24    101.41   153870.0    WST
...             ...      ...     ...       ...        ...    ...
2023-11-28   352.35   356.79  350.74    352.42   468210.0    WST
2023-11-29   355.43   355.97  348.55    348.92   378334.0    WST
2023-11-30   348.23   351.35  346.57    350.76   640480.0    WST
2023-12-01   350.31   355.17  348.96    351.79   271839.0    WST
2023-12-04   349.26   354.02  346.81    350.88   435693.0    WST

[1491 rows x 6 columns],             1. open  2. high    3. low  4. close  5. volume Ticker
date
2018-01-02    85.20    86.12   84.9300     85.53   328464.0    RMD
2018-01-03    85.38    86.65   85.3100     86.42   480780.0    RMD
2018-01-04    86.54    86.85   86.2300     86.54   627529.0    RMD
2018-01-05    86.59    87.69   86.1200     87.69   531585.0    RMD
2018-01-08    87.67    88.49   87.2400     88.19   713552.0    RMD
...             ...      ...       ...       ...        ...    ...
2023-11-28   151.95   155.99  151.9500    155.68  1358140.0    RMD
2023-11-29   158.50   164.10  158.4800    158.85  1762127.0    RMD
2023-11-30   159.25   160.16  156.6725    157.73  1641217.0    RMD
2023-12-01   157.45   159.74  156.3900    159.64   704931.0    RMD
2023-12-04   160.84   162.48  159.6000    161.53  1103146.0    RMD

[1491 rows x 6 columns],             1. open  2. high    3. low  4. close  5. volume Ticker
date
2018-01-02   221.02   222.45  220.0000    221.16  3276075.0    UNH
2018-01-03   221.62   223.81  220.5200    223.48  2353723.0    UNH
2018-01-04   224.34   226.10  224.1700    224.45  2643607.0    UNH
2018-01-05   225.19   229.05  224.7200    228.73  2385007.0    UNH
2018-01-08   228.13   228.71  224.6100    224.76  2730381.0    UNH
...             ...      ...       ...       ...        ...    ...
2023-11-28   545.63   545.82  540.0700    540.53  2859309.0    UNH
2023-11-29   530.00   541.86  528.6500    534.98  4549977.0    UNH
2023-11-30   535.79   553.94  534.0100    552.97  7121207.0    UNH
2023-12-01   550.42   554.70  545.1600    547.16  3462153.0    UNH
2023-12-04   548.26   551.87  543.0351    548.28  2709303.0    UNH

[1491 rows x 6 columns],             1. open  2. high   3. low  4. close  5. volume Ticker
date
2018-01-02   225.00  226.600  223.750    226.00  1175943.0    ELV
2018-01-03   227.87  229.550  225.060    229.15  1302005.0    ELV
2018-01-04   229.60  231.410  228.860    230.21  1017834.0    ELV
2018-01-05   230.19  234.540  229.880    234.34  1345404.0    ELV
2018-01-08   233.49  233.490  230.730    231.82  1629128.0    ELV
...             ...      ...      ...       ...        ...    ...
2023-11-28   477.32  480.210  475.290    475.49   767739.0    ELV
2023-11-29   469.61  472.689  462.740    465.36  1687845.0    ELV
2023-11-30   467.66  480.470  465.090    479.49  2083833.0    ELV
2023-12-01   478.42  485.220  478.420    483.12  1361515.0    ELV
2023-12-04   483.27  485.640  477.575    483.10   877778.0    ELV

[1491 rows x 6 columns],             1. open  2. high  3. low  4. close   5. volume Ticker
date
2018-01-02    73.06  74.0300  72.870     73.52   5697104.0    CVS
2018-01-03    73.73  73.9000  73.060     73.20   6136065.0    CVS
2018-01-04    75.19  76.6700  74.680     75.13  13695605.0    CVS
2018-01-05    76.31  78.5600  76.140     78.45  14240985.0    CVS
2018-01-08    78.32  78.7800  77.150     77.77   9581927.0    CVS
...             ...      ...     ...       ...         ...    ...
2023-11-28    68.86  69.5300  68.600     69.32   4291910.0    CVS
2023-11-29    68.74  68.9100  66.850     66.90   9856309.0    CVS
2023-11-30    67.10  68.0472  66.710     67.95  12331263.0    CVS
2023-12-01    67.91  68.6400  67.365     68.48   7094672.0    CVS
2023-12-04    68.41  69.4800  67.770     68.48   7413614.0    CVS

[1491 rows x 6 columns],             1. open  2. high    3. low  4. close  5. volume Ticker
date
2018-01-02   204.14   204.98  202.3400    202.56  1114845.0     CI
2018-01-03   202.52   206.32  201.3000    205.96  1360756.0     CI
2018-01-04   206.07   208.04  206.0700    207.04   870097.0     CI
2018-01-05   207.91   211.08  207.6000    210.55   742822.0     CI
2018-01-08   209.77   210.49  207.7100    208.22  1100255.0     CI
...             ...      ...       ...       ...        ...    ...
2023-11-28   287.03   289.04  285.3500    286.08  1437048.0     CI
2023-11-29   283.15   287.60  262.5100    262.87  7568667.0     CI
2023-11-30   263.89   266.91  259.4200    262.88  7046791.0     CI
2023-12-01   263.96   273.13  263.7901    269.02  3401904.0     CI
2023-12-04   268.25   269.88  261.1000    262.91  3027834.0     CI

[1491 rows x 6 columns],             1. open  2. high  3. low  4. close  5. volume Ticker
date
2018-01-02  249.360   252.86  248.01    251.64   795680.0    HUM
2018-01-03  252.030   256.60  250.25    251.28  1212312.0    HUM
2018-01-04  252.860   259.97  252.86    258.36  1345052.0    HUM
2018-01-05  258.420   264.90  258.39    264.33  1212204.0    HUM
2018-01-08  263.880   263.88  257.05    258.55  1303905.0    HUM
...             ...      ...     ...       ...        ...    ...
2023-11-28  511.840   515.39  510.37    510.45   718133.0    HUM
2023-11-29  496.010   526.47  480.36    482.41  5041754.0    HUM
2023-11-30  483.915   489.58  478.09    484.86  4128271.0    HUM
2023-12-01  483.030   504.79  480.49    495.21  2178657.0    HUM
2023-12-04  496.000   498.77  486.72    491.98  1119391.0    HUM

[1491 rows x 6 columns],             1. open  2. high  3. low  4. close  5. volume Ticker
date
2018-01-02    54.49   54.520   53.99     54.16   741402.0    NVO
2018-01-03    54.54   54.750   54.38     54.68   752381.0    NVO
2018-01-04    54.65   54.680   54.36     54.49   604232.0    NVO
2018-01-05    54.47   54.760   54.45     54.74   645393.0    NVO
2018-01-08    54.56   54.740   54.38     54.69   614045.0    NVO
...             ...      ...     ...       ...        ...    ...
2023-11-28   101.87  102.250  101.03    101.43  5147734.0    NVO
2023-11-29   101.55  102.310  100.86    102.00  2664643.0    NVO
2023-11-30   101.49  101.990  101.01    101.84  2671120.0    NVO
2023-12-01   101.10  101.760  100.31    100.40  4567522.0    NVO
2023-12-04   100.57  101.145   99.58    100.92  2987971.0    NVO

[1491 rows x 6 columns],             1. open  2. high   3. low  4. close  5. volume Ticker
date
2018-01-02   150.00   153.30  147.720    152.91  1322844.0   VRTX
2018-01-03   153.50   153.50  148.580    152.01  1601041.0   VRTX
2018-01-04   153.39   153.97  151.630    153.07  1340181.0   VRTX
2018-01-05   155.54   157.35  154.100    155.69  1857324.0   VRTX
2018-01-08   155.15   157.21  153.350    156.89  1917306.0   VRTX
...             ...      ...      ...       ...        ...    ...
2023-11-28   350.32   353.03  346.285    347.04  1154122.0   VRTX
2023-11-29   347.50   353.60  346.680    351.00  1497318.0   VRTX
2023-11-30   352.79   355.37  350.190    354.81  1636953.0   VRTX
2023-12-01   355.11   356.71  350.225    351.16  1135104.0   VRTX
2023-12-04   349.00   352.90  347.510    350.63  1469512.0   VRTX

[1491 rows x 6 columns],             1. open  2. high   3. low  4. close  5. volume Ticker
date
2018-01-02   379.48  384.810  377.105    382.60   615937.0   REGN
2018-01-03   383.14  396.780  381.140    393.78   687986.0   REGN
2018-01-04   394.50  394.950  382.400    382.95   644172.0   REGN
2018-01-05   385.85  388.790  381.950    385.10   447465.0   REGN
2018-01-08   384.40  387.330  371.260    372.52  1067679.0   REGN
...             ...      ...      ...       ...        ...    ...
2023-11-28   796.23  801.630  792.570    801.14   446730.0   REGN
2023-11-29   804.17  814.300  800.240    808.59   627657.0   REGN
2023-11-30   811.78  828.855  810.250    823.81   954624.0   REGN
2023-12-01   824.94  828.420  808.890    814.86   560248.0   REGN
2023-12-04   804.55  824.610  802.550    823.32   508434.0   REGN

[1491 rows x 6 columns],             1. open  2. high    3. low  4. close  5. volume Ticker
date
2018-01-02    53.64   56.510   53.6300     56.13   945253.0   SGEN
2018-01-03    56.30   57.130   55.5450     56.61   540620.0   SGEN
2018-01-04    56.74   56.875   55.0400     55.53   577182.0   SGEN
2018-01-05    55.98   55.980   54.8700     55.01   500198.0   SGEN
2018-01-08    55.12   55.230   54.2950     54.68   807795.0   SGEN
...             ...      ...       ...       ...        ...    ...
2023-11-28   214.42  214.690  213.8397    214.16   873892.0   SGEN
2023-11-29   214.33  214.650  213.5000    213.52   742965.0   SGEN
2023-11-30   213.60  213.950  212.8200    213.21  1395313.0   SGEN
2023-12-01   213.60  213.970  212.4400    212.72  1304127.0   SGEN
2023-12-04   212.72  213.245  212.5250    213.13   769645.0   SGEN

[1491 rows x 6 columns],             1. open  2. high  3. low  4. close   5. volume Ticker
date
2018-12-07    22.00   22.750   18.51     18.60  12995569.0   MRNA
2018-12-10    18.90   19.439   18.00     18.80   4233345.0   MRNA
2018-12-11    20.55   20.660   17.99     18.01   3435271.0   MRNA
2018-12-12    18.55   19.480   18.02     18.68   2590873.0   MRNA
2018-12-13    19.25   19.290   18.68     18.76   1608629.0   MRNA
...             ...      ...     ...       ...         ...    ...
2023-11-28    77.32   78.250   75.84     78.18   2240038.0   MRNA
2023-11-29    78.95   80.890   78.85     79.01   2569849.0   MRNA
2023-11-30    79.63   80.200   77.52     77.70   3314985.0   MRNA
2023-12-01    76.58   80.260   74.50     79.83   3958346.0   MRNA
2023-12-04    79.56   80.730   77.66     79.87   3171966.0   MRNA

[1256 rows x 6 columns],             1. open  2. high  3. low  4. close    5. volume Ticker
date
2018-01-02    36.38    36.52  36.240     36.44   14503068.0    PFE
2018-01-03    36.45    36.77  36.230     36.71   13453369.0    PFE
2018-01-04    36.71    36.92  36.600     36.79   12350187.0    PFE
2018-01-05    36.82    36.88  36.610     36.86   12380571.0    PFE
2018-01-08    36.72    36.80  36.330     36.45   18908870.0    PFE
...             ...      ...     ...       ...          ...    ...
2023-11-28    30.11    30.11  29.635     29.69   29497713.0    PFE
2023-11-29    29.77    30.22  29.725     30.08   26185160.0    PFE
2023-11-30    30.31    30.51  29.960     30.47   45356593.0    PFE
2023-12-01    28.97    29.40  28.300     28.91  103624040.0    PFE
2023-12-04    29.02    29.64  29.020     29.28   47410449.0    PFE

[1491 rows x 6 columns],             1. open  2. high  3. low  4. close   5. volume Ticker
date
2018-01-02   139.66   139.95  138.72    139.23   6835739.0    JNJ
2018-01-03   139.36   140.68  138.90    140.56   5241755.0    JNJ
2018-01-04   140.45   141.14  140.22    140.55   4777518.0    JNJ
2018-01-05   140.69   141.82  140.28    141.71   5900718.0    JNJ
2018-01-08   141.70   142.00  140.92    141.89   4980217.0    JNJ
...             ...      ...     ...       ...         ...    ...
2023-11-28   151.40   151.81  150.84    151.63   5909044.0    JNJ
2023-11-29   151.33   152.20  151.07    152.11   5190026.0    JNJ
2023-11-30   152.26   155.14  151.92    154.66  12481867.0    JNJ
2023-12-01   156.44   158.46  155.47    158.38  10342901.0    JNJ
2023-12-04   158.00   160.02  158.00    158.88   8920279.0    JNJ

[1491 rows x 6 columns],             1. open   2. high    3. low  4. close  5. volume Ticker
date
2018-01-02    84.46   85.0000   84.0600     84.68  3455236.0    LLY
2018-01-03    84.74   85.4200   84.2700     85.14  3068865.0    LLY
2018-01-04    85.28   85.8000   84.7400     85.52  2459830.0    LLY
2018-01-05    86.09   86.7500   85.9300     86.57  2910172.0    LLY
2018-01-08    86.69   86.7100   85.4000     86.13  3015436.0    LLY
...             ...       ...       ...       ...        ...    ...
2023-11-28   592.00  595.3800  589.3600    591.60  1793933.0    LLY
2023-11-29   592.20  594.5399  584.4401    591.86  1908649.0    LLY
2023-11-30   591.46  596.2300  586.2100    591.04  5658350.0    LLY
2023-12-01   591.70  601.9700  583.0000    584.04  3638565.0    LLY
2023-12-04   582.13  587.0900  574.3300    585.68  2577122.0    LLY

[1491 rows x 6 columns],             1. open  2. high  3. low  4. close  5. volume Ticker
date
2018-01-02    35.24   35.440  34.950     35.38  6107393.0    AZN
2018-01-03    35.22   35.510  35.160     35.45  4195423.0    AZN
2018-01-04    35.51   35.600  35.280     35.50  3870932.0    AZN
2018-01-05    35.58   35.920  35.500     35.87  3336132.0    AZN
2018-01-08    35.72   35.770  35.420     35.62  1826353.0    AZN
...             ...      ...     ...       ...        ...    ...
2023-11-28    63.20   63.530  63.090     63.30  5556087.0    AZN
2023-11-29    64.14   64.335  63.710     64.12  8493239.0    AZN
2023-11-30    63.97   64.900  63.790     64.59  9991508.0    AZN
2023-12-01    64.59   65.060  64.365     64.79  3616434.0    AZN
2023-12-04    64.87   65.110  64.610     65.02  3340280.0    AZN

[1491 rows x 6 columns],             1. open   2. high  3. low  4. close   5. volume Ticker
date
2018-01-02    56.59   56.7500   56.05     56.22  10048319.0    MRK
2018-01-03    56.23   56.2600   55.96     56.14  10573680.0    MRK
2018-01-04    56.44   57.4200   56.38     57.05  14991734.0    MRK
2018-01-05    57.39   57.3900   56.59     56.99   9482639.0    MRK
2018-01-08    57.21   57.2500   56.50     56.66  10504085.0    MRK
...             ...       ...     ...       ...         ...    ...
2023-11-28   101.31  101.3500  100.01    100.18   8738483.0    MRK
2023-11-29   100.28  101.1700   99.80    101.13  10286779.0    MRK
2023-11-30   100.84  102.6850  100.28    102.48  29299666.0    MRK
2023-12-01   102.85  103.6761  102.66    103.46   6863429.0    MRK
2023-12-04   103.73  105.3791  103.73    105.06  10169907.0    MRK

[1491 rows x 6 columns]]

In [5]:
# Concatenate the list of dataframes into a single dataframe
result_df = pd.concat(whole_data)

# Save the dataframe to a CSV file
result_df.to_csv('Healthcare_Stock_Data.csv', index=True)

In [6]:
# Read the CSV file into a DataFrame
healthcare_stock_data = pd.read_csv('Healthcare_Stock_Data.csv')

# Create dictionaries to map symbols to sectors and industries
symbol_to_sector = {
    "ISRG": "Healthcare",
    "BDX": "Healthcare",
    "ALC": "Healthcare",
    "WST": "Healthcare",
    "RMD": "Healthcare",
    "UNH": "Healthcare",
    "ELV": "Healthcare",
    "CVS": "Healthcare",
    "CI": "Healthcare",
    "HUM": "Healthcare",
    "NVO": "Healthcare",
    "VRTX": "Healthcare",
    "REGN": "Healthcare",
    "SGEN": "Healthcare",
    "MRNA": "Healthcare",
    "PFE": "Healthcare",
    "JNJ": "Healthcare",
    "LLY": "Healthcare",
    "AZN": "Healthcare",
    "MRK": "Healthcare",
}

symbol_to_industry = {
    "ISRG": "Medical Instruments & supplies",
    "BDX": "Medical Instruments & supplies",
    "ALC": "Medical Instruments & supplies",
    "WST": "Medical Instruments & supplies",
    "RMD": "Medical Instruments & supplies",
    "UNH": "Healthcare plans",
    "ELV": "Healthcare plans",
    "CVS": "Healthcare plans",
    "CI": "Healthcare plans",
    "HUM": "Healthcare plans",
    "NVO": "Biotechnology",
    "VRTX": "Biotechnology",
    "REGN": "Biotechnology",
    "SGEN": "Biotechnology",
    "MRNA": "Biotechnology",
    "PFE": "Drug Manufacturers",
    "JNJ": "Drug Manufacturers",
    "LLY": "Drug Manufacturers",
    "AZN": "Drug Manufacturers",
    "MRK": "Drug Manufacturers",
}

# Add 'Sector' and 'Industry' columns based on the mappings
healthcare_stock_data['Sector'] = healthcare_stock_data['Ticker'].map(symbol_to_sector)
healthcare_stock_data['Industry'] = healthcare_stock_data['Ticker'].map(symbol_to_industry)

# Display the updated DataFrame
healthcare_stock_data.head()

,date,1. open,2. high,3. low,4. close,5. volume,Ticker,Sector,Industry
0,2018-01-02,367.89,375.81,365.11,375.25,694925.0,ISRG,Healthcare,Medical Instruments & supplies
1,2018-01-03,377.12,384.17,375.01,383.82,767711.0,ISRG,Healthcare,Medical Instruments & supplies
2,2018-01-04,385.73,389.48,375.09,376.92,889251.0,ISRG,Healthcare,Medical Instruments & supplies
3,2018-01-05,380.88,380.88,375.80,379.01,672195.0,ISRG,Healthcare,Medical Instruments & supplies
4,2018-01-08,378.72,392.64,377.21,391.86,938767.0,ISRG,Healthcare,Medical Instruments & supplies

In [9]:

# Convert 'Date' column to datetime type
healthcare_stock_data['Date'] = pd.to_datetime(healthcare_stock_data['Date'], format='%Y-%m-%d')

# Rename columns
healthcare_stock_data = healthcare_stock_data.rename(columns={
    '1. open': "Open",
    '2. high': "High",
    '3. low': "Low",
    '4. close': "Close",
    '5. volume': "Volume"
})

# Print the updated DataFrame
healthcare_stock_data

healthcare_stock_data

,Date,Open,High,Low,Close,Volume,Ticker,Sector,Industry
0,2018-01-02,367.89,375.8100,365.11,375.25,694925.0,ISRG,Healthcare,Medical Instruments & supplies
1,2018-01-03,377.12,384.1700,375.01,383.82,767711.0,ISRG,Healthcare,Medical Instruments & supplies
2,2018-01-04,385.73,389.4800,375.09,376.92,889251.0,ISRG,Healthcare,Medical Instruments & supplies
3,2018-01-05,380.88,380.8800,375.80,379.01,672195.0,ISRG,Healthcare,Medical Instruments & supplies
4,2018-01-08,378.72,392.6400,377.21,391.86,938767.0,ISRG,Healthcare,Medical Instruments & supplies
...,...,...,...,...,...,...,...,...,...
29262,2023-11-28,101.31,101.3500,100.01,100.18,8738483.0,MRK,Healthcare,Drug Manufacturers
29263,2023-11-29,100.28,101.1700,99.80,101.13,10286779.0,MRK,Healthcare,Drug Manufacturers
29264,2023-11-30,100.84,102.6850,100.28,102.48,29299666.0,MRK,Healthcare,Drug Manufacturers
29265,2023-12-01,102.85,103.6761,102.66,103.46,6863429.0,MRK,Healthcare,Drug Manufacturers
29266,2023-12-04,103.73,105.3791,103.73,105.06,10169907.0,MRK,Healthcare,Drug Manufacturers

In [10]:


# Reorder columns
healthcare_stock_data = healthcare_stock_data[['Date', 'Ticker', 'Sector', 'Industry', 'Open', 'High', 'Low', 'Close', 'Volume']]

# Print the updated DataFrame
healthcare_stock_data

,Date,Ticker,Sector,Industry,Open,High,Low,Close,Volume
0,2018-01-02,ISRG,Healthcare,Medical Instruments & supplies,367.89,375.8100,365.11,375.25,694925.0
1,2018-01-03,ISRG,Healthcare,Medical Instruments & supplies,377.12,384.1700,375.01,383.82,767711.0
2,2018-01-04,ISRG,Healthcare,Medical Instruments & supplies,385.73,389.4800,375.09,376.92,889251.0
3,2018-01-05,ISRG,Healthcare,Medical Instruments & supplies,380.88,380.8800,375.80,379.01,672195.0
4,2018-01-08,ISRG,Healthcare,Medical Instruments & supplies,378.72,392.6400,377.21,391.86,938767.0
...,...,...,...,...,...,...,...,...,...
29262,2023-11-28,MRK,Healthcare,Drug Manufacturers,101.31,101.3500,100.01,100.18,8738483.0
29263,2023-11-29,MRK,Healthcare,Drug Manufacturers,100.28,101.1700,99.80,101.13,10286779.0
29264,2023-11-30,MRK,Healthcare,Drug Manufacturers,100.84,102.6850,100.28,102.48,29299666.0
29265,2023-12-01,MRK,Healthcare,Drug Manufacturers,102.85,103.6761,102.66,103.46,6863429.0
29266,2023-12-04,MRK,Healthcare,Drug Manufacturers,103.73,105.3791,103.73,105.06,10169907.0

In [5]:
# Save the dataframe to a CSV file
df_reordered.to_csv('Healthcare_Stock_Data4.csv', index=False)